apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sysdig-assessment
  region: us-west-2
  version: "1.31"

managedNodeGroups:
  - name: ng-1
    instanceType: t3.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 30
    privateNetworking: false
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        ebs: true
        efs: true
        albIngress: true

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
